### ISSUE TITLE
Add syntax matches for curly braces

### ISSUE THREAD

**Issue by Soupertonic** [zzzyxwvut/java-vim#2]
I'm creating my own color scheme right now and I'm unable to assign curly braces any color, except by assining it to the `Normal` group which has plenty of side effects. I'd kindly ask to add syntax matches for `{` and `}`.

And I did inspect the curly braces. For curly braces within a class, it does get recognized (but apparently gets overwritten again?)
<img width="280" alt="Screenshot 2024-09-12 at 14 44 46" src="https://github.com/user-attachments/assets/3b6ae348-f68c-469b-8dea-88539d783181">

Inspecting a curly brace at class declaration, it doesn't get recognized though.
<img width="365" alt="Screenshot 2024-09-12 at 14 46 02" src="https://github.com/user-attachments/assets/890943b0-fcc4-436a-9b59-cb350eb4b544">

What I'm trying to achieve is assigning the curly braces the same colors as the parentheses. I'd like to give semicolons and any other kind of punctuation/delimiters a color too but there are no highlight groups available and the standard `Delimiter` highlight group is simply ignored, or rather overwritten by `javaBlock`. 

<img width="521" alt="Screenshot 2024-09-12 at 14 50 24" src="https://github.com/user-attachments/assets/086a7bd2-38ff-4242-99d3-095d382eb64e">

**Comment by zzzyxwvut** [comment]
> For curly braces within a class, it does get recognized (but apparently gets overwritten again?)

That is the effect of making `javaBlock` `:syn-transparent` and  
not assigning any `:syn-matchgroup` to `:syn-start`.

I have drafted [a PR](https://github.com/zzzyxwvut/java-vim/pull/3), give it a try.

After adding these commands to `~/.vim/after/syntax/java.vim`:

```vim
setl fdm=syntax fdc=2 fdl=8
hi link javaParen1 javaParen
hi link javaParen2 javaParen
hi link javaBlockOther javaParen
hi link javaBlockStart javaParen
hi link javaDocCodeTag javaParen
hi link javaParen Todo
syn match javaSeparator "[;,]" containedin=javaAnnotation
hi link javaSeparator Error
```

and writing the drafted `java.vim` in `~/.vim/syntax/`, this  
is what I get:

![braces_tests](https://github.com/user-attachments/assets/1c13050a-e408-4c2c-86c6-407db0933b11)

with this command:

```shell
vim --clean --cmd 'set rtp^=~/.vim,~/.vim/after' \
  --cmd 'let g:java_highlight_functions = "style"' /tmp/BracesTests.java
```

for this source file:

```java

// let g:java_highlight_functions = 'style'
// setl fdm=syntax fdc=2 fdl=8
// hi link javaParen1 javaParen
// hi link javaParen2 javaParen
// hi link javaBlockOther javaParen
// hi link javaBlockStart javaParen
// hi link javaDocCodeTag javaParen
// hi link javaParen Todo
// syn match javaSeparator "[;,]" containedin=javaAnnotation
// hi link javaSeparator Error
class BracesTests
{
	/**
	 * Starts listening to {@code PlayerSpawnEvent}s.
	 *
	 * {@inheritDoc}
	 */
	@SuppressWarnings({
		"foo",
		"bar",
		"baz",
		"quux"
	})
	static void listenToPlayerSpawnEvents(EventHandler globalEventHandler)
	{
		java.util.Objects.requireNonNull(globalEventHandler,
							"globalEventHandler")
			.addListener(PlayerSpawnEvent.class, event -> {
				event.getPlayer().teleport(new Pos(0, 40, 0));
		});
	}

	interface EventHandler	{ void addListener(Class<? extends Event> k,
				java.util.function.Consumer<? super Event> a); }
	interface Event		{ Player getPlayer(); }
	interface PlayerSpawnEvent extends Event { }
	static abstract class Player	{ abstract void teleport(Pos pos); }
	record Pos(int x, int y, int z) { }
}
```

Is this is what you are after, modulo the choice of colours?

------------------------------------------------------------

I'm afraid you'll be on your own with your punctuational  
endeavours.

In general, the usual recourse for later defined syntax  
items that are overruled by earlier defined syntax items  
written elsewhere is to `:syn clear overrulingItem`, define  
your later item, and then redefine the cleared earlier item.

See also `:syn-priority`.

**Comment by zzzyxwvut** [comment]
Thus, you can switch from `Normal` to e.g. `CursorLine` uniform  
highlighting for block braces by linking the following two  
groups in `~/.vim/after/syntax/java.vim`:

```vim
highlight link javaBlockOtherStart CursorLine
highlight link javaBlockStart CursorLine
```
